BadWords = [
    "nigger",
    "nigga",
    "niggers",
    "niggas",
    "niggs",
    "niger",
    "faggot",
    "fag",
    "nigg",
    "sex",
    " cp ",
    "child",
    "porn",
    "dick",
    "penis",
    "nig/ger",
    "nig/ga",
    " rape ",
    "retard",
    "retarded",
    "retards",
    "isis",
    "allahu",
    "akbar",
    "besatiality",
    "buttfuck",
    "circlejerk",
    "cum",
    "cummer",
    "cumming",
    "cumshot",
    "dicks",
    "dildo",
    "ejaculating",
    "ejaculation",
    "ejaculat",
    "fuk",
    "gangbang",
    "gay",
    "horny",
    "pussy",
    "vagina",
    "jackoff",
    " kkk ",
    "jizz",
    " kum ",
    "molest",
    "molester",
    "pedo",
    "pedophile",
    "pissing",
    "piss",
    "pornography",
    "sperm",
    "cock",
    "69420",
    "6969",
    "69 69",
    " 420 ",
    "hentai",
    "yaoi",
    "protogen",
    "furry",
    "boobs",
    "boob",
    "nipples",
    "nipple",
    "negro",
    "n1gg3r",
    ".ct8",
    "ct8",
    ".pl",
    "hitler"
]

ExtendedBadWords = [
    "fuck",
    "fucking",
    "fucks",
    "shit",
    "horny"
]