[package]
name = "CorePackages"
author = "Roblox"
license = ""
version = "0.1.0"
proxy = "https://github.com/roblox/rotriever-proxy-index"

[dependencies]
Roact = "github.com/roblox/roact@1.2"
Rodux = "github.com/roblox/rodux@1.0"
RoactRodux = "github.com/roblox/roact-rodux@0.2"
RoactNavigation = "github.com/roblox/roact-navigation@0.2"
Cryo = "github.com/roblox/cryo@1.0"
LuaChatDeps = { git = "https://github.rbx.com/Roblox/lua-chat-deps" }
LuaDiscussionsDeps = { git = "https://github.rbx.com/Roblox/lua-discussions-deps" }
LuaSocialLibrariesDeps = { git = "https://github.rbx.com/Roblox/lua-social-libraries-deps" }
PremiumUpsellDeps = { git = "https://github.com/Roblox/premium-upsell-deps" }
AvatarExperienceDeps = { git = "https://github.com/Roblox/avatar-experience-deps" }
UIBlox = { git = "https://github.com/Roblox/uiblox", rev = "master" }
Otter = "github.com/roblox/otter@0.1"
t = "github.com/roblox/t@1.0"
enumerate = "github.com/roblox/enumerate@1.0.0"
PolicyProvider = { git = "https://github.com/Roblox/lua-roact-policy-provider", rev = "master" }
Lumberyak = { git = "https://github.rbx.com/Roblox/lumberyak" }
StringUtilities = "github.com/Roblox/string-utilities@1.0.0"
UrlBuilder = "github.com/Roblox/url-builder@1.0.1"

# The following packages were ported from AppTempCommon
Promise = { git = "https://github.rbx.com/Roblox/lua-promise" }
Result = { git = "https://github.rbx.com/Roblox/lua-result" }
tutils = { git = "https://github.rbx.com/Roblox/tutils" }

PurchasePrompt = { git = "https://github.com/Roblox/PurchasePromptScript-Roact", rev = "master" }

InGameMenuDependencies = { git = "https://github.rbx.com/Roblox/in-game-menu-dependencies", rev = "master" }

RoactGamepad = "github.com/roblox/roact-gamepad@0.4.4"

[dev_dependencies]
TestEZ = "github.com/roblox/testez@0.3.1"
Rhodium = "github.com/roblox/rhodium@0.2.5"

[patch."https://github.rbx.com/roblox/uiblox"]
git = "https://github.com/roblox/uiblox"
rev = "master"

[patch."https://github.com/roblox/roact"]
target = "github.com/roblox/roact"
version = "1.2"

[patch."https://github.com/roblox/cryo"]
target = "github.com/roblox/cryo"
version = "1.0"

[patch."https://github.com/roblox/t"]
target = "github.com/roblox/t"
version = "1.0"

[patch."https://github.com/roblox/rodux"]
target = "github.com/roblox/rodux"
version = "1.0"

[patch."https://github.com/roblox/otter"]
target = "github.com/roblox/otter"
version = "0.1"
