local GuiService = game:GetService("GuiService")

local IMAGE_SHEET = "rbxasset://textures/AvatarEditorImages/Sheet.png"

local AESpriteSheet = {
	["dragger-highlight"] = {
		name = "dragger-highlight",
		filename = "1x/dragger-highlight.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(627, 69),
		image = IMAGE_SHEET,
	},
	["dragger"] = {
		name = "dragger",
		filename = "1x/dragger.png",
		imageRectSize = Vector2.new(32, 32),
		imageRectOffset = Vector2.new(1968, 31),
		image = IMAGE_SHEET,
	},
	["gr-category-selector"] = {
		name = "gr-category-selector",
		filename = "1x/gr-category-selector.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(913, 69),
		image = IMAGE_SHEET,
	},
	["gr-circle-shadow"] = {
		name = "gr-circle-shadow",
		filename = "1x/gr-circle-shadow.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1351, 185),
		image = IMAGE_SHEET,
	},
	["gr-circle-white"] = {
		name = "gr-circle-white",
		filename = "1x/gr-circle-white.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(477, 69),
		image = IMAGE_SHEET,
	},
	["gr-orange-circle"] = {
		name = "gr-orange-circle",
		filename = "1x/gr-orange-circle.png",
		imageRectSize = Vector2.new(52, 52),
		imageRectOffset = Vector2.new(1015, 69),
		image = IMAGE_SHEET,
	},
	["gr-ring-selector"] = {
		name = "gr-ring-selector",
		filename = "1x/gr-ring-selector.png",
		imageRectSize = Vector2.new(54, 54),
		imageRectOffset = Vector2.new(1069, 69),
		image = IMAGE_SHEET,
	},
	["ic-color-on"] = {
		name = "ic-color-on",
		filename = "1x/ic-color-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(211, 31),
		image = IMAGE_SHEET,
	},
	["ic-color"] = {
		name = "ic-color",
		filename = "1x/ic-color.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(301, 31),
		image = IMAGE_SHEET,
	},
	["dragger-highlight@2x"] = {
		name = "dragger-highlight@2x",
		filename = "2x/dragger-highlight@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(799, 573),
		image = IMAGE_SHEET,
	},
	["dragger@2x"] = {
		name = "dragger@2x",
		filename = "2x/dragger@2x.png",
		imageRectSize = Vector2.new(64, 64),
		imageRectOffset = Vector2.new(1885, 243),
		image = IMAGE_SHEET,
	},
	["gr-category-selector@2x"] = {
		name = "gr-category-selector@2x",
		filename = "2x/gr-category-selector@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(603, 573),
		image = IMAGE_SHEET,
	},
	["gr-circle-shadow@2x"] = {
		name = "gr-circle-shadow@2x",
		filename = "2x/gr-circle-shadow@2x.png",
		imageRectSize = Vector2.new(112, 112),
		imageRectOffset = Vector2.new(1903, 573),
		image = IMAGE_SHEET,
	},
	["gr-circle-white@2x"] = {
		name = "gr-circle-white@2x",
		filename = "2x/gr-circle-white@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(897, 573),
		image = IMAGE_SHEET,
	},
	["gr-orange-circle@2x"] = {
		name = "gr-orange-circle@2x",
		filename = "2x/gr-orange-circle@2x.png",
		imageRectSize = Vector2.new(104, 104),
		imageRectOffset = Vector2.new(1687, 573),
		image = IMAGE_SHEET,
	},
	["gr-ring-selector@2x"] = {
		name = "gr-ring-selector@2x",
		filename = "2x/gr-ring-selector@2x.png",
		imageRectSize = Vector2.new(108, 108),
		imageRectOffset = Vector2.new(1793, 573),
		image = IMAGE_SHEET,
	},
	["ic-color-on@2x"] = {
		name = "ic-color-on@2x",
		filename = "2x/ic-color-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 185),
		image = IMAGE_SHEET,
	},
	["ic-color@2x"] = {
		name = "ic-color@2x",
		filename = "2x/ic-color@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 185),
		image = IMAGE_SHEET,
	},
	["ic-shirt-on@2x"] = {
		name = "ic-shirt-on@2x",
		filename = "2x/ic-shirt-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 243),
		image = IMAGE_SHEET,
	},
	["ic-shirt@2x"] = {
		name = "ic-shirt@2x",
		filename = "2x/ic-shirt@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1393, 243),
		image = IMAGE_SHEET,
	},
	["ic-shoulder-on@2x"] = {
		name = "ic-shoulder-on@2x",
		filename = "2x/ic-shoulder-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 243),
		image = IMAGE_SHEET,
	},
	["ic-shoulder@2x"] = {
		name = "ic-shoulder@2x",
		filename = "2x/ic-shoulder@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1589, 69),
		image = IMAGE_SHEET,
	},
	["dragger-highlight@3x"] = {
		name = "dragger-highlight@3x",
		filename = "3x/dragger-highlight@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1497, 687),
		image = IMAGE_SHEET,
	},
	["dragger@3x"] = {
		name = "dragger@3x",
		filename = "3x/dragger@3x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(1387, 573),
		image = IMAGE_SHEET,
	},
	["gr-box-shadow@3x"] = {
		name = "gr-box-shadow@3x",
		filename = "3x/gr-box-shadow@3x.png",
		imageRectSize = Vector2.new(36, 36),
		imageRectOffset = Vector2.new(2002, 31),
		image = IMAGE_SHEET,
	},
	["gr-circle-shadow@3x"] = {
		name = "gr-circle-shadow@3x",
		filename = "3x/gr-circle-shadow@3x.png",
		imageRectSize = Vector2.new(168, 168),
		imageRectOffset = Vector2.new(331, 839),
		image = IMAGE_SHEET,
	},
	["gr-circle-white@3x"] = {
		name = "gr-circle-white@3x",
		filename = "3x/gr-circle-white@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1351, 687),
		image = IMAGE_SHEET,
	},
	["gr-ring-selector@3x"] = {
		name = "gr-ring-selector@3x",
		filename = "3x/gr-ring-selector@3x.png",
		imageRectSize = Vector2.new(162, 162),
		imageRectOffset = Vector2.new(1, 839),
		image = IMAGE_SHEET,
	},
	["ic-color-on@3x"] = {
		name = "ic-color-on@3x",
		filename = "3x/ic-color-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 487),
		image = IMAGE_SHEET,
	},
	["ic-color@3x"] = {
		name = "ic-color@3x",
		filename = "3x/ic-color@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1463, 401),
		image = IMAGE_SHEET,
	},
	["ctn-primary nav"] = {
		name = "ctn-primary nav",
		filename = "graphic/navigation/ctn-primary nav.png",
		imageRectSize = Vector2.new(98, 99),
		imageRectOffset = Vector2.new(1485, 573),
		image = IMAGE_SHEET,
	},
	["ctn-primary nav@2x"] = {
		name = "ctn-primary nav@2x",
		filename = "graphic/navigation/ctn-primary nav@2x.png",
		imageRectSize = Vector2.new(196, 198),
		imageRectOffset = Vector2.new(1411, 839),
		image = IMAGE_SHEET,
	},
	["ctn-primary nav@3x"] = {
		name = "ctn-primary nav@3x",
		filename = "graphic/navigation/ctn-primary nav@3x.png",
		imageRectSize = Vector2.new(294, 297),
		imageRectOffset = Vector2.new(249, 1057),
		image = IMAGE_SHEET,
	},
	["ring1"] = {
		name = "ring1",
		filename = "graphic/ring/ring1.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1509, 243),
		image = IMAGE_SHEET,
	},
	["ring1@2x"] = {
		name = "ring1@2x",
		filename = "graphic/ring/ring1@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(473, 687),
		image = IMAGE_SHEET,
	},
	["ring1@3x"] = {
		name = "ring1@3x",
		filename = "graphic/ring/ring1@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(683, 839),
		image = IMAGE_SHEET,
	},
	["ring2"] = {
		name = "ring2",
		filename = "graphic/ring/ring2.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1571, 243),
		image = IMAGE_SHEET,
	},
	["ring2@2x"] = {
		name = "ring2@2x",
		filename = "graphic/ring/ring2@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(351, 687),
		image = IMAGE_SHEET,
	},
	["ring2@3x"] = {
		name = "ring2@3x",
		filename = "graphic/ring/ring2@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(501, 839),
		image = IMAGE_SHEET,
	},
	["ring3"] = {
		name = "ring3",
		filename = "graphic/ring/ring3.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1757, 243),
		image = IMAGE_SHEET,
	},
	["ring3@2x"] = {
		name = "ring3@2x",
		filename = "graphic/ring/ring3@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(229, 687),
		image = IMAGE_SHEET,
	},
	["ring3@3x"] = {
		name = "ring3@3x",
		filename = "graphic/ring/ring3@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(1229, 839),
		image = IMAGE_SHEET,
	},
	["ring4"] = {
		name = "ring4",
		filename = "graphic/ring/ring4.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1633, 243),
		image = IMAGE_SHEET,
	},
	["ring4@2x"] = {
		name = "ring4@2x",
		filename = "graphic/ring/ring4@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(717, 687),
		image = IMAGE_SHEET,
	},
	["ring4@3x"] = {
		name = "ring4@3x",
		filename = "graphic/ring/ring4@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(1047, 839),
		image = IMAGE_SHEET,
	},
	["ring5"] = {
		name = "ring5",
		filename = "graphic/ring/ring5.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1695, 243),
		image = IMAGE_SHEET,
	},
	["ring5@2x"] = {
		name = "ring5@2x",
		filename = "graphic/ring/ring5@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(595, 687),
		image = IMAGE_SHEET,
	},
	["ring5@3x"] = {
		name = "ring5@3x",
		filename = "graphic/ring/ring5@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(865, 839),
		image = IMAGE_SHEET,
	},
	["icon-border-on"] = {
		name = "icon-border-on",
		filename = "graphic/selector/icon-border-on.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(427, 69),
		image = IMAGE_SHEET,
	},
	["icon-border-on@2x"] = {
		name = "icon-border-on@2x",
		filename = "graphic/selector/icon-border-on@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(1191, 573),
		image = IMAGE_SHEET,
	},
	["icon-border-on@3x"] = {
		name = "icon-border-on@3x",
		filename = "graphic/selector/icon-border-on@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1059, 687),
		image = IMAGE_SHEET,
	},
	["icon-border"] = {
		name = "icon-border",
		filename = "graphic/selector/icon-border.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(577, 69),
		image = IMAGE_SHEET,
	},
	["icon-border@2x"] = {
		name = "icon-border@2x",
		filename = "graphic/selector/icon-border@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(1289, 573),
		image = IMAGE_SHEET,
	},
	["icon-border@3x"] = {
		name = "icon-border@3x",
		filename = "graphic/selector/icon-border@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1205, 687),
		image = IMAGE_SHEET,
	},
	["btn-toggle"] = {
		name = "btn-toggle",
		filename = "graphic/switch/btn-toggle.png",
		imageRectSize = Vector2.new(25, 24),
		imageRectOffset = Vector2.new(376, 1),
		sliceCenter = Rect.new(12, 11, 13, 13),
		image = IMAGE_SHEET,
	},
	["btn-toggle@2x"] = {
		name = "btn-toggle@2x",
		filename = "graphic/switch/btn-toggle@2x.png",
		imageRectSize = Vector2.new(50, 48),
		imageRectOffset = Vector2.new(861, 69),
		sliceCenter = Rect.new(24, 22, 26, 26),
		image = IMAGE_SHEET,
	},
	["btn-toggle@3x"] = {
		name = "btn-toggle@3x",
		filename = "graphic/switch/btn-toggle@3x.png",
		imageRectSize = Vector2.new(75, 72),
		imageRectOffset = Vector2.new(1, 315),
		sliceCenter = Rect.new(36, 33, 39, 39),
		image = IMAGE_SHEET,
	},
	["ctn-toggle"] = {
		name = "ctn-toggle",
		filename = "graphic/switch/ctn-toggle.png",
		imageRectSize = Vector2.new(29, 28),
		imageRectOffset = Vector2.new(667, 31),
		sliceCenter = Rect.new(14, 13, 15, 15),
		image = IMAGE_SHEET,
	},
	["ctn-toggle@2x"] = {
		name = "ctn-toggle@2x",
		filename = "graphic/switch/ctn-toggle@2x.png",
		imageRectSize = Vector2.new(58, 56),
		imageRectOffset = Vector2.new(1291, 185),
		sliceCenter = Rect.new(28, 26, 30, 30),
		image = IMAGE_SHEET,
	},
	["ctn-toggle@3x"] = {
		name = "ctn-toggle@3x",
		filename = "graphic/switch/ctn-toggle@3x.png",
		imageRectSize = Vector2.new(87, 84),
		imageRectOffset = Vector2.new(1440, 315),
		sliceCenter = Rect.new(42, 39, 45, 45),
		image = IMAGE_SHEET,
	},
	["ic-climb-on"] = {
		name = "ic-climb-on",
		filename = "Icon/Navigation/animations/ic-climb-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(451, 31),
		image = IMAGE_SHEET,
	},
	["ic-climb-on@2x"] = {
		name = "ic-climb-on@2x",
		filename = "Icon/Navigation/animations/ic-climb-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1641, 185),
		image = IMAGE_SHEET,
	},
	["ic-climb-on@3x"] = {
		name = "ic-climb-on@3x",
		filename = "Icon/Navigation/animations/ic-climb-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(173, 487),
		image = IMAGE_SHEET,
	},
	["ic-climb"] = {
		name = "ic-climb",
		filename = "Icon/Navigation/animations/ic-climb.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(151, 31),
		image = IMAGE_SHEET,
	},
	["ic-climb@2x"] = {
		name = "ic-climb@2x",
		filename = "Icon/Navigation/animations/ic-climb@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1757, 185),
		image = IMAGE_SHEET,
	},
	["ic-climb@3x"] = {
		name = "ic-climb@3x",
		filename = "Icon/Navigation/animations/ic-climb@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(431, 487),
		image = IMAGE_SHEET,
	},
	["ic-fall-on"] = {
		name = "ic-fall-on",
		filename = "Icon/Navigation/animations/ic-fall-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(241, 31),
		image = IMAGE_SHEET,
	},
	["ic-fall-on@2x"] = {
		name = "ic-fall-on@2x",
		filename = "Icon/Navigation/animations/ic-fall-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(233, 185),
		image = IMAGE_SHEET,
	},
	["ic-fall-on@3x"] = {
		name = "ic-fall-on@3x",
		filename = "Icon/Navigation/animations/ic-fall-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(517, 401),
		image = IMAGE_SHEET,
	},
	["ic-fall"] = {
		name = "ic-fall",
		filename = "Icon/Navigation/animations/ic-fall.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(61, 31),
		image = IMAGE_SHEET,
	},
	["ic-fall@2x"] = {
		name = "ic-fall@2x",
		filename = "Icon/Navigation/animations/ic-fall@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(291, 185),
		image = IMAGE_SHEET,
	},
	["ic-fall@3x"] = {
		name = "ic-fall@3x",
		filename = "Icon/Navigation/animations/ic-fall@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(775, 401),
		image = IMAGE_SHEET,
	},
	["ic-idle-on"] = {
		name = "ic-idle-on",
		filename = "Icon/Navigation/animations/ic-idle-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1501, 1),
		image = IMAGE_SHEET,
	},
	["ic-idle-on@2x"] = {
		name = "ic-idle-on@2x",
		filename = "Icon/Navigation/animations/ic-idle-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1567, 127),
		image = IMAGE_SHEET,
	},
	["ic-idle-on@3x"] = {
		name = "ic-idle-on@3x",
		filename = "Icon/Navigation/animations/ic-idle-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(259, 573),
		image = IMAGE_SHEET,
	},
	["ic-idle"] = {
		name = "ic-idle",
		filename = "Icon/Navigation/animations/ic-idle.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1591, 1),
		image = IMAGE_SHEET,
	},
	["ic-idle@2x"] = {
		name = "ic-idle@2x",
		filename = "Icon/Navigation/animations/ic-idle@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1509, 127),
		image = IMAGE_SHEET,
	},
	["ic-idle@3x"] = {
		name = "ic-idle@3x",
		filename = "Icon/Navigation/animations/ic-idle@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(345, 573),
		image = IMAGE_SHEET,
	},
	["ic-jump-on"] = {
		name = "ic-jump-on",
		filename = "Icon/Navigation/animations/ic-jump-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1088, 31),
		image = IMAGE_SHEET,
	},
	["ic-jump-on@2x"] = {
		name = "ic-jump-on@2x",
		filename = "Icon/Navigation/animations/ic-jump-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1335, 243),
		image = IMAGE_SHEET,
	},
	["ic-jump-on@3x"] = {
		name = "ic-jump-on@3x",
		filename = "Icon/Navigation/animations/ic-jump-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(87, 573),
		image = IMAGE_SHEET,
	},
	["ic-jump"] = {
		name = "ic-jump",
		filename = "Icon/Navigation/animations/ic-jump.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1028, 31),
		image = IMAGE_SHEET,
	},
	["ic-jump@2x"] = {
		name = "ic-jump@2x",
		filename = "Icon/Navigation/animations/ic-jump@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(639, 243),
		image = IMAGE_SHEET,
	},
	["ic-jump@3x"] = {
		name = "ic-jump@3x",
		filename = "Icon/Navigation/animations/ic-jump@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(861, 487),
		image = IMAGE_SHEET,
	},
	["ic-run-on"] = {
		name = "ic-run-on",
		filename = "Icon/Navigation/animations/ic-run-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(913, 1),
		image = IMAGE_SHEET,
	},
	["ic-run-on@2x"] = {
		name = "ic-run-on@2x",
		filename = "Icon/Navigation/animations/ic-run-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1393, 127),
		image = IMAGE_SHEET,
	},
	["ic-run-on@3x"] = {
		name = "ic-run-on@3x",
		filename = "Icon/Navigation/animations/ic-run-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1377, 487),
		image = IMAGE_SHEET,
	},
	["ic-run"] = {
		name = "ic-run",
		filename = "Icon/Navigation/animations/ic-run.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(883, 1),
		image = IMAGE_SHEET,
	},
	["ic-run@2x"] = {
		name = "ic-run@2x",
		filename = "Icon/Navigation/animations/ic-run@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1277, 243),
		image = IMAGE_SHEET,
	},
	["ic-run@3x"] = {
		name = "ic-run@3x",
		filename = "Icon/Navigation/animations/ic-run@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1807, 401),
		image = IMAGE_SHEET,
	},
	["ic-swim-on"] = {
		name = "ic-swim-on",
		filename = "Icon/Navigation/animations/ic-swim-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1531, 1),
		image = IMAGE_SHEET,
	},
	["ic-swim-on@2x"] = {
		name = "ic-swim-on@2x",
		filename = "Icon/Navigation/animations/ic-swim-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(987, 127),
		image = IMAGE_SHEET,
	},
	["ic-swim-on@3x"] = {
		name = "ic-swim-on@3x",
		filename = "Icon/Navigation/animations/ic-swim-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(322, 315),
		image = IMAGE_SHEET,
	},
	["ic-swim"] = {
		name = "ic-swim",
		filename = "Icon/Navigation/animations/ic-swim.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1561, 1),
		image = IMAGE_SHEET,
	},
	["ic-swim@2x"] = {
		name = "ic-swim@2x",
		filename = "Icon/Navigation/animations/ic-swim@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(581, 127),
		image = IMAGE_SHEET,
	},
	["ic-swim@3x"] = {
		name = "ic-swim@3x",
		filename = "Icon/Navigation/animations/ic-swim@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(408, 315),
		image = IMAGE_SHEET,
	},
	["ic-walk-on"] = {
		name = "ic-walk-on",
		filename = "Icon/Navigation/animations/ic-walk-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1471, 1),
		image = IMAGE_SHEET,
	},
	["ic-walk-on@2x"] = {
		name = "ic-walk-on@2x",
		filename = "Icon/Navigation/animations/ic-walk-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(465, 127),
		image = IMAGE_SHEET,
	},
	["ic-walk-on@3x"] = {
		name = "ic-walk-on@3x",
		filename = "Icon/Navigation/animations/ic-walk-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1701, 315),
		image = IMAGE_SHEET,
	},
	["ic-walk"] = {
		name = "ic-walk",
		filename = "Icon/Navigation/animations/ic-walk.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1409, 1),
		image = IMAGE_SHEET,
	},
	["ic-walk@2x"] = {
		name = "ic-walk@2x",
		filename = "Icon/Navigation/animations/ic-walk@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 127),
		image = IMAGE_SHEET,
	},
	["ic-walk@3x"] = {
		name = "ic-walk@3x",
		filename = "Icon/Navigation/animations/ic-walk@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1873, 315),
		image = IMAGE_SHEET,
	},
	["ic-head-on"] = {
		name = "ic-head-on",
		filename = "Icon/Navigation/body/ic-head-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1243, 1),
		image = IMAGE_SHEET,
	},
	["ic-head-on@2x"] = {
		name = "ic-head-on@2x",
		filename = "Icon/Navigation/body/ic-head-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(929, 127),
		image = IMAGE_SHEET,
	},
	["ic-head-on@3x"] = {
		name = "ic-head-on@3x",
		filename = "Icon/Navigation/body/ic-head-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(431, 573),
		image = IMAGE_SHEET,
	},
	["ic-head"] = {
		name = "ic-head",
		filename = "Icon/Navigation/body/ic-head.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1208, 31),
		image = IMAGE_SHEET,
	},
	["ic-head@2x"] = {
		name = "ic-head@2x",
		filename = "Icon/Navigation/body/ic-head@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1741, 127),
		image = IMAGE_SHEET,
	},
	["ic-head@3x"] = {
		name = "ic-head@3x",
		filename = "Icon/Navigation/body/ic-head@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(173, 573),
		image = IMAGE_SHEET,
	},
	["ic-left-arms-on"] = {
		name = "ic-left-arms-on",
		filename = "Icon/Navigation/body/ic-left-arms-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1289, 1),
		image = IMAGE_SHEET,
	},
	["ic-left-arms-on@2x"] = {
		name = "ic-left-arms-on@2x",
		filename = "Icon/Navigation/body/ic-left-arms-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(697, 127),
		image = IMAGE_SHEET,
	},
	["ic-left-arms-on@3x"] = {
		name = "ic-left-arms-on@3x",
		filename = "Icon/Navigation/body/ic-left-arms-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1119, 487),
		image = IMAGE_SHEET,
	},
	["ic-left-arms"] = {
		name = "ic-left-arms",
		filename = "Icon/Navigation/body/ic-left-arms.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1379, 1),
		image = IMAGE_SHEET,
	},
	["ic-left-arms@2x"] = {
		name = "ic-left-arms@2x",
		filename = "Icon/Navigation/body/ic-left-arms@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(407, 127),
		image = IMAGE_SHEET,
	},
	["ic-left-arms@3x"] = {
		name = "ic-left-arms@3x",
		filename = "Icon/Navigation/body/ic-left-arms@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 573),
		image = IMAGE_SHEET,
	},
	["ic-left-legs-on"] = {
		name = "ic-left-legs-on",
		filename = "Icon/Navigation/body/ic-left-legs-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1319, 1),
		image = IMAGE_SHEET,
	},
	["ic-left-legs-on@2x"] = {
		name = "ic-left-legs-on@2x",
		filename = "Icon/Navigation/body/ic-left-legs-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(639, 127),
		image = IMAGE_SHEET,
	},
	["ic-left-legs-on@3x"] = {
		name = "ic-left-legs-on@3x",
		filename = "Icon/Navigation/body/ic-left-legs-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1033, 487),
		image = IMAGE_SHEET,
	},
	["ic-left-legs"] = {
		name = "ic-left-legs",
		filename = "Icon/Navigation/body/ic-left-legs.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1448, 31),
		image = IMAGE_SHEET,
	},
	["ic-left-legs@2x"] = {
		name = "ic-left-legs@2x",
		filename = "Icon/Navigation/body/ic-left-legs@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 243),
		image = IMAGE_SHEET,
	},
	["ic-left-legs@3x"] = {
		name = "ic-left-legs@3x",
		filename = "Icon/Navigation/body/ic-left-legs@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1205, 487),
		image = IMAGE_SHEET,
	},
	["ic-right-arms-on"] = {
		name = "ic-right-arms-on",
		filename = "Icon/Navigation/body/ic-right-arms-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1349, 1),
		image = IMAGE_SHEET,
	},
	["ic-right-arms-on@2x"] = {
		name = "ic-right-arms-on@2x",
		filename = "Icon/Navigation/body/ic-right-arms-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1451, 127),
		image = IMAGE_SHEET,
	},
	["ic-right-arms-on@3x"] = {
		name = "ic-right-arms-on@3x",
		filename = "Icon/Navigation/body/ic-right-arms-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1721, 487),
		image = IMAGE_SHEET,
	},
	["ic-right-arms"] = {
		name = "ic-right-arms",
		filename = "Icon/Navigation/body/ic-right-arms.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1621, 1),
		image = IMAGE_SHEET,
	},
	["ic-right-arms@2x"] = {
		name = "ic-right-arms@2x",
		filename = "Icon/Navigation/body/ic-right-arms@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 127),
		image = IMAGE_SHEET,
	},
	["ic-right-arms@3x"] = {
		name = "ic-right-arms@3x",
		filename = "Icon/Navigation/body/ic-right-arms@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1893, 487),
		image = IMAGE_SHEET,
	},
	["ic-right-legs-on"] = {
		name = "ic-right-legs-on",
		filename = "Icon/Navigation/body/ic-right-legs-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1681, 1),
		image = IMAGE_SHEET,
	},
	["ic-right-legs-on@2x"] = {
		name = "ic-right-legs-on@2x",
		filename = "Icon/Navigation/body/ic-right-legs-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1161, 127),
		image = IMAGE_SHEET,
	},
	["ic-right-legs-on@3x"] = {
		name = "ic-right-legs-on@3x",
		filename = "Icon/Navigation/body/ic-right-legs-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1635, 487),
		image = IMAGE_SHEET,
	},
	["ic-right-legs"] = {
		name = "ic-right-legs",
		filename = "Icon/Navigation/body/ic-right-legs.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1183, 1),
		image = IMAGE_SHEET,
	},
	["ic-right-legs@2x"] = {
		name = "ic-right-legs@2x",
		filename = "Icon/Navigation/body/ic-right-legs@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(407, 243),
		image = IMAGE_SHEET,
	},
	["ic-right-legs@3x"] = {
		name = "ic-right-legs@3x",
		filename = "Icon/Navigation/body/ic-right-legs@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1463, 487),
		image = IMAGE_SHEET,
	},
	["ic-scale-on"] = {
		name = "ic-scale-on",
		filename = "Icon/Navigation/body/ic-scale-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1821, 1),
		image = IMAGE_SHEET,
	},
	["ic-scale-on@2x"] = {
		name = "ic-scale-on@2x",
		filename = "Icon/Navigation/body/ic-scale-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1219, 127),
		image = IMAGE_SHEET,
	},
	["ic-scale-on@3x"] = {
		name = "ic-scale-on@3x",
		filename = "Icon/Navigation/body/ic-scale-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(603, 487),
		image = IMAGE_SHEET,
	},
	["ic-scale"] = {
		name = "ic-scale",
		filename = "Icon/Navigation/body/ic-scale.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(853, 1),
		image = IMAGE_SHEET,
	},
	["ic-scale@2x"] = {
		name = "ic-scale@2x",
		filename = "Icon/Navigation/body/ic-scale@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1219, 243),
		image = IMAGE_SHEET,
	},
	["ic-scale@3x"] = {
		name = "ic-scale@3x",
		filename = "Icon/Navigation/body/ic-scale@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1615, 315),
		image = IMAGE_SHEET,
	},
	["ic-skintone-on"] = {
		name = "ic-skintone-on",
		filename = "Icon/Navigation/body/ic-skintone-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(211, 31),
		image = IMAGE_SHEET,
	},
	["ic-skintone-on@2x"] = {
		name = "ic-skintone-on@2x",
		filename = "Icon/Navigation/body/ic-skintone-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 185),
		image = IMAGE_SHEET,
	},
	["ic-skintone-on@3x"] = {
		name = "ic-skintone-on@3x",
		filename = "Icon/Navigation/body/ic-skintone-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 487),
		image = IMAGE_SHEET,
	},
	["ic-skintone"] = {
		name = "ic-skintone",
		filename = "Icon/Navigation/body/ic-skintone.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(301, 31),
		image = IMAGE_SHEET,
	},
	["ic-skintone@2x"] = {
		name = "ic-skintone@2x",
		filename = "Icon/Navigation/body/ic-skintone@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 185),
		image = IMAGE_SHEET,
	},
	["ic-skintone@3x"] = {
		name = "ic-skintone@3x",
		filename = "Icon/Navigation/body/ic-skintone@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1463, 401),
		image = IMAGE_SHEET,
	},
	["ic-torso-on"] = {
		name = "ic-torso-on",
		filename = "Icon/Navigation/body/ic-torso-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1851, 1),
		image = IMAGE_SHEET,
	},
	["ic-torso-on@2x"] = {
		name = "ic-torso-on@2x",
		filename = "Icon/Navigation/body/ic-torso-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(349, 127),
		image = IMAGE_SHEET,
	},
	["ic-torso-on@3x"] = {
		name = "ic-torso-on@3x",
		filename = "Icon/Navigation/body/ic-torso-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(236, 315),
		image = IMAGE_SHEET,
	},
	["ic-torso"] = {
		name = "ic-torso",
		filename = "Icon/Navigation/body/ic-torso.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1093, 1),
		image = IMAGE_SHEET,
	},
	["ic-torso@2x"] = {
		name = "ic-torso@2x",
		filename = "Icon/Navigation/body/ic-torso@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1, 127),
		image = IMAGE_SHEET,
	},
	["ic-torso@3x"] = {
		name = "ic-torso@3x",
		filename = "Icon/Navigation/body/ic-torso@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(494, 315),
		image = IMAGE_SHEET,
	},
	["ic-back-on"] = {
		name = "ic-back-on",
		filename = "Icon/Navigation/clothing/ic-back-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1911, 1),
		image = IMAGE_SHEET,
	},
	["ic-back-on@2x"] = {
		name = "ic-back-on@2x",
		filename = "Icon/Navigation/clothing/ic-back-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1299, 69),
		image = IMAGE_SHEET,
	},
	["ic-back-on@3x"] = {
		name = "ic-back-on@3x",
		filename = "Icon/Navigation/clothing/ic-back-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1549, 401),
		image = IMAGE_SHEET,
	},
	["ic-back"] = {
		name = "ic-back",
		filename = "Icon/Navigation/clothing/ic-back.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(938, 31),
		image = IMAGE_SHEET,
	},
	["ic-back@2x"] = {
		name = "ic-back@2x",
		filename = "Icon/Navigation/clothing/ic-back@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1989, 185),
		image = IMAGE_SHEET,
	},
	["ic-back@3x"] = {
		name = "ic-back@3x",
		filename = "Icon/Navigation/clothing/ic-back@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1377, 401),
		image = IMAGE_SHEET,
	},
	["ic-face-accessories-on"] = {
		name = "ic-face-accessories-on",
		filename = "Icon/Navigation/clothing/ic-face-accessories-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(2001, 1),
		image = IMAGE_SHEET,
	},
	["ic-face-accessories-on@2x"] = {
		name = "ic-face-accessories-on@2x",
		filename = "Icon/Navigation/clothing/ic-face-accessories-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1531, 69),
		image = IMAGE_SHEET,
	},
	["ic-face-accessories-on@3x"] = {
		name = "ic-face-accessories-on@3x",
		filename = "Icon/Navigation/clothing/ic-face-accessories-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1268, 315),
		image = IMAGE_SHEET,
	},
	["ic-face-accessories"] = {
		name = "ic-face-accessories",
		filename = "Icon/Navigation/clothing/ic-face-accessories.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1941, 1),
		image = IMAGE_SHEET,
	},
	["ic-face-accessories@2x"] = {
		name = "ic-face-accessories@2x",
		filename = "Icon/Navigation/clothing/ic-face-accessories@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1647, 69),
		image = IMAGE_SHEET,
	},
	["ic-face-accessories@3x"] = {
		name = "ic-face-accessories@3x",
		filename = "Icon/Navigation/clothing/ic-face-accessories@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1354, 315),
		image = IMAGE_SHEET,
	},
	["ic-face-on"] = {
		name = "ic-face-on",
		filename = "Icon/Navigation/clothing/ic-face-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(331, 31),
		image = IMAGE_SHEET,
	},
	["ic-face-on@2x"] = {
		name = "ic-face-on@2x",
		filename = "Icon/Navigation/clothing/ic-face-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1915, 127),
		image = IMAGE_SHEET,
	},
	["ic-face-on@3x"] = {
		name = "ic-face-on@3x",
		filename = "Icon/Navigation/clothing/ic-face-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 401),
		image = IMAGE_SHEET,
	},
	["ic-face"] = {
		name = "ic-face",
		filename = "Icon/Navigation/clothing/ic-face.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(271, 31),
		image = IMAGE_SHEET,
	},
	["ic-face@2x"] = {
		name = "ic-face@2x",
		filename = "Icon/Navigation/clothing/ic-face@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1857, 127),
		image = IMAGE_SHEET,
	},
	["ic-face@3x"] = {
		name = "ic-face@3x",
		filename = "Icon/Navigation/clothing/ic-face@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1959, 315),
		image = IMAGE_SHEET,
	},
	["ic-front-on"] = {
		name = "ic-front-on",
		filename = "Icon/Navigation/clothing/ic-front-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1971, 1),
		image = IMAGE_SHEET,
	},
	["ic-front-on@2x"] = {
		name = "ic-front-on@2x",
		filename = "Icon/Navigation/clothing/ic-front-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1473, 69),
		image = IMAGE_SHEET,
	},
	["ic-front-on@3x"] = {
		name = "ic-front-on@3x",
		filename = "Icon/Navigation/clothing/ic-front-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1033, 401),
		image = IMAGE_SHEET,
	},
	["ic-front"] = {
		name = "ic-front",
		filename = "Icon/Navigation/clothing/ic-front.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1628, 31),
		image = IMAGE_SHEET,
	},
	["ic-front@2x"] = {
		name = "ic-front@2x",
		filename = "Icon/Navigation/clothing/ic-front@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(697, 185),
		image = IMAGE_SHEET,
	},
	["ic-front@3x"] = {
		name = "ic-front@3x",
		filename = "Icon/Navigation/clothing/ic-front@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(947, 401),
		image = IMAGE_SHEET,
	},
	["ic-gear-on"] = {
		name = "ic-gear-on",
		filename = "Icon/Navigation/clothing/ic-gear-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1881, 1),
		image = IMAGE_SHEET,
	},
	["ic-gear-on@2x"] = {
		name = "ic-gear-on@2x",
		filename = "Icon/Navigation/clothing/ic-gear-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1125, 69),
		image = IMAGE_SHEET,
	},
	["ic-gear-on@3x"] = {
		name = "ic-gear-on@3x",
		filename = "Icon/Navigation/clothing/ic-gear-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1119, 401),
		image = IMAGE_SHEET,
	},
	["ic-gear"] = {
		name = "ic-gear",
		filename = "Icon/Navigation/clothing/ic-gear.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1658, 31),
		image = IMAGE_SHEET,
	},
	["ic-gear@2x"] = {
		name = "ic-gear@2x",
		filename = "Icon/Navigation/clothing/ic-gear@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 185),
		image = IMAGE_SHEET,
	},
	["ic-gear@3x"] = {
		name = "ic-gear@3x",
		filename = "Icon/Navigation/clothing/ic-gear@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(861, 401),
		image = IMAGE_SHEET,
	},
	["ic-hair-on"] = {
		name = "ic-hair-on",
		filename = "Icon/Navigation/clothing/ic-hair-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1213, 1),
		image = IMAGE_SHEET,
	},
	["ic-hair-on@2x"] = {
		name = "ic-hair-on@2x",
		filename = "Icon/Navigation/clothing/ic-hair-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(523, 127),
		image = IMAGE_SHEET,
	},
	["ic-hair-on@3x"] = {
		name = "ic-hair-on@3x",
		filename = "Icon/Navigation/clothing/ic-hair-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(689, 401),
		image = IMAGE_SHEET,
	},
	["ic-hair"] = {
		name = "ic-hair",
		filename = "Icon/Navigation/clothing/ic-hair.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1688, 31),
		image = IMAGE_SHEET,
	},
	["ic-hair@2x"] = {
		name = "ic-hair@2x",
		filename = "Icon/Navigation/clothing/ic-hair@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(523, 185),
		image = IMAGE_SHEET,
	},
	["ic-hair@3x"] = {
		name = "ic-hair@3x",
		filename = "Icon/Navigation/clothing/ic-hair@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(603, 401),
		image = IMAGE_SHEET,
	},
	["ic-hat-on"] = {
		name = "ic-hat-on",
		filename = "Icon/Navigation/clothing/ic-hat-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1718, 31),
		image = IMAGE_SHEET,
	},
	["ic-hat-on@2x"] = {
		name = "ic-hat-on@2x",
		filename = "Icon/Navigation/clothing/ic-hat-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(349, 185),
		image = IMAGE_SHEET,
	},
	["ic-hat-on@3x"] = {
		name = "ic-hat-on@3x",
		filename = "Icon/Navigation/clothing/ic-hat-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(87, 401),
		image = IMAGE_SHEET,
	},
	["ic-hat"] = {
		name = "ic-hat",
		filename = "Icon/Navigation/clothing/ic-hat.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1058, 31),
		image = IMAGE_SHEET,
	},
	["ic-hat@2x"] = {
		name = "ic-hat@2x",
		filename = "Icon/Navigation/clothing/ic-hat@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(465, 185),
		image = IMAGE_SHEET,
	},
	["ic-hat@3x"] = {
		name = "ic-hat@3x",
		filename = "Icon/Navigation/clothing/ic-hat@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(517, 573),
		image = IMAGE_SHEET,
	},
	["ic-neck-on"] = {
		name = "ic-neck-on",
		filename = "Icon/Navigation/clothing/ic-neck-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1651, 1),
		image = IMAGE_SHEET,
	},
	["ic-neck-on@2x"] = {
		name = "ic-neck-on@2x",
		filename = "Icon/Navigation/clothing/ic-neck-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1357, 69),
		image = IMAGE_SHEET,
	},
	["ic-neck-on@3x"] = {
		name = "ic-neck-on@3x",
		filename = "Icon/Navigation/clothing/ic-neck-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(947, 487),
		image = IMAGE_SHEET,
	},
	["ic-neck"] = {
		name = "ic-neck",
		filename = "Icon/Navigation/clothing/ic-neck.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1478, 31),
		image = IMAGE_SHEET,
	},
	["ic-neck@2x"] = {
		name = "ic-neck@2x",
		filename = "Icon/Navigation/clothing/ic-neck@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(813, 243),
		image = IMAGE_SHEET,
	},
	["ic-neck@3x"] = {
		name = "ic-neck@3x",
		filename = "Icon/Navigation/clothing/ic-neck@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1182, 315),
		image = IMAGE_SHEET,
	},
	["ic-pants-on"] = {
		name = "ic-pants-on",
		filename = "Icon/Navigation/clothing/ic-pants-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1711, 1),
		image = IMAGE_SHEET,
	},
	["ic-pants-on@2x"] = {
		name = "ic-pants-on@2x",
		filename = "Icon/Navigation/clothing/ic-pants-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1415, 69),
		image = IMAGE_SHEET,
	},
	["ic-pants-on@3x"] = {
		name = "ic-pants-on@3x",
		filename = "Icon/Navigation/clothing/ic-pants-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(689, 487),
		image = IMAGE_SHEET,
	},
	["ic-pants"] = {
		name = "ic-pants",
		filename = "Icon/Navigation/clothing/ic-pants.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1388, 31),
		image = IMAGE_SHEET,
	},
	["ic-pants@2x"] = {
		name = "ic-pants@2x",
		filename = "Icon/Navigation/clothing/ic-pants@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(697, 243),
		image = IMAGE_SHEET,
	},
	["ic-pants@3x"] = {
		name = "ic-pants@3x",
		filename = "Icon/Navigation/clothing/ic-pants@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1291, 487),
		image = IMAGE_SHEET,
	},
	["ic-shirts-on"] = {
		name = "ic-shirts-on",
		filename = "Icon/Navigation/clothing/ic-shirts-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(793, 1),
		image = IMAGE_SHEET,
	},
	["ic-shirts-on@2x"] = {
		name = "ic-shirts-on@2x",
		filename = "Icon/Navigation/clothing/ic-shirts-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 243),
		image = IMAGE_SHEET,
	},
	["ic-shirts-on@3x"] = {
		name = "ic-shirts-on@3x",
		filename = "Icon/Navigation/clothing/ic-shirts-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(580, 315),
		image = IMAGE_SHEET,
	},
	["ic-shirts"] = {
		name = "ic-shirts",
		filename = "Icon/Navigation/clothing/ic-shirts.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(763, 1),
		image = IMAGE_SHEET,
	},
	["ic-shirts@2x"] = {
		name = "ic-shirts@2x",
		filename = "Icon/Navigation/clothing/ic-shirts@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1393, 243),
		image = IMAGE_SHEET,
	},
	["ic-shirts@3x"] = {
		name = "ic-shirts@3x",
		filename = "Icon/Navigation/clothing/ic-shirts@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(752, 315),
		image = IMAGE_SHEET,
	},
	["ic-shoulders-on"] = {
		name = "ic-shoulders-on",
		filename = "Icon/Navigation/clothing/ic-shoulders-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1761, 1),
		image = IMAGE_SHEET,
	},
	["ic-shoulders-on@2x"] = {
		name = "ic-shoulders-on@2x",
		filename = "Icon/Navigation/clothing/ic-shoulders-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1277, 127),
		image = IMAGE_SHEET,
	},
	["ic-shoulders-on@3x"] = {
		name = "ic-shoulders-on@3x",
		filename = "Icon/Navigation/clothing/ic-shoulders-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(924, 315),
		image = IMAGE_SHEET,
	},
	["ic-shoulders"] = {
		name = "ic-shoulders",
		filename = "Icon/Navigation/clothing/ic-shoulders.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1063, 1),
		image = IMAGE_SHEET,
	},
	["ic-shoulders@2x"] = {
		name = "ic-shoulders@2x",
		filename = "Icon/Navigation/clothing/ic-shoulders@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1589, 69),
		image = IMAGE_SHEET,
	},
	["ic-shoulders@3x"] = {
		name = "ic-shoulders@3x",
		filename = "Icon/Navigation/clothing/ic-shoulders@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(838, 315),
		image = IMAGE_SHEET,
	},
	["ic-waist-on"] = {
		name = "ic-waist-on",
		filename = "Icon/Navigation/clothing/ic-waist-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(613, 1),
		image = IMAGE_SHEET,
	},
	["ic-waist-on@2x"] = {
		name = "ic-waist-on@2x",
		filename = "Icon/Navigation/clothing/ic-waist-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1625, 127),
		image = IMAGE_SHEET,
	},
	["ic-waist-on@3x"] = {
		name = "ic-waist-on@3x",
		filename = "Icon/Navigation/clothing/ic-waist-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1010, 315),
		image = IMAGE_SHEET,
	},
	["ic-waist"] = {
		name = "ic-waist",
		filename = "Icon/Navigation/clothing/ic-waist.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(643, 1),
		image = IMAGE_SHEET,
	},
	["ic-waist@2x"] = {
		name = "ic-waist@2x",
		filename = "Icon/Navigation/clothing/ic-waist@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(813, 127),
		image = IMAGE_SHEET,
	},
	["ic-waist@3x"] = {
		name = "ic-waist@3x",
		filename = "Icon/Navigation/clothing/ic-waist@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1787, 315),
		image = IMAGE_SHEET,
	},
	["ic-all-on"] = {
		name = "ic-all-on",
		filename = "Icon/Navigation/primary/ic-all-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(673, 1),
		image = IMAGE_SHEET,
	},
	["ic-all-on@2x"] = {
		name = "ic-all-on@2x",
		filename = "Icon/Navigation/primary/ic-all-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(871, 127),
		image = IMAGE_SHEET,
	},
	["ic-all-on@3x"] = {
		name = "ic-all-on@3x",
		filename = "Icon/Navigation/primary/ic-all-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1529, 315),
		image = IMAGE_SHEET,
	},
	["ic-all"] = {
		name = "ic-all",
		filename = "Icon/Navigation/primary/ic-all.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(481, 31),
		image = IMAGE_SHEET,
	},
	["ic-all@2x"] = {
		name = "ic-all@2x",
		filename = "Icon/Navigation/primary/ic-all@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1103, 185),
		image = IMAGE_SHEET,
	},
	["ic-all@3x"] = {
		name = "ic-all@3x",
		filename = "Icon/Navigation/primary/ic-all@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1721, 401),
		image = IMAGE_SHEET,
	},
	["ic-animations-on"] = {
		name = "ic-animations-on",
		filename = "Icon/Navigation/primary/ic-animations-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(913, 1),
		image = IMAGE_SHEET,
	},
	["ic-animations-on@2x"] = {
		name = "ic-animations-on@2x",
		filename = "Icon/Navigation/primary/ic-animations-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(987, 243),
		image = IMAGE_SHEET,
	},
	["ic-animations-on@3x"] = {
		name = "ic-animations-on@3x",
		filename = "Icon/Navigation/primary/ic-animations-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1635, 401),
		image = IMAGE_SHEET,
	},
	["ic-animations"] = {
		name = "ic-animations",
		filename = "Icon/Navigation/primary/ic-animations.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(883, 1),
		image = IMAGE_SHEET,
	},
	["ic-animations@2x"] = {
		name = "ic-animations@2x",
		filename = "Icon/Navigation/primary/ic-animations@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1277, 243),
		image = IMAGE_SHEET,
	},
	["ic-animations@3x"] = {
		name = "ic-animations@3x",
		filename = "Icon/Navigation/primary/ic-animations@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1807, 401),
		image = IMAGE_SHEET,
	},
	["ic-body-on"] = {
		name = "ic-body-on",
		filename = "Icon/Navigation/primary/ic-body-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(848, 31),
		image = IMAGE_SHEET,
	},
	["ic-body-on@2x"] = {
		name = "ic-body-on@2x",
		filename = "Icon/Navigation/primary/ic-body-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(59, 243),
		image = IMAGE_SHEET,
	},
	["ic-body-on@3x"] = {
		name = "ic-body-on@3x",
		filename = "Icon/Navigation/primary/ic-body-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1291, 401),
		image = IMAGE_SHEET,
	},
	["ic-body"] = {
		name = "ic-body",
		filename = "Icon/Navigation/primary/ic-body.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(788, 31),
		image = IMAGE_SHEET,
	},
	["ic-body@2x"] = {
		name = "ic-body@2x",
		filename = "Icon/Navigation/primary/ic-body@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1, 243),
		image = IMAGE_SHEET,
	},
	["ic-body@3x"] = {
		name = "ic-body@3x",
		filename = "Icon/Navigation/primary/ic-body@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1893, 401),
		image = IMAGE_SHEET,
	},
	["ic-clothing-on"] = {
		name = "ic-clothing-on",
		filename = "Icon/Navigation/primary/ic-clothing-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(698, 31),
		image = IMAGE_SHEET,
	},
	["ic-clothing-on@2x"] = {
		name = "ic-clothing-on@2x",
		filename = "Icon/Navigation/primary/ic-clothing-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1103, 127),
		image = IMAGE_SHEET,
	},
	["ic-clothing-on@3x"] = {
		name = "ic-clothing-on@3x",
		filename = "Icon/Navigation/primary/ic-clothing-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(517, 487),
		image = IMAGE_SHEET,
	},
	["ic-clothing"] = {
		name = "ic-clothing",
		filename = "Icon/Navigation/primary/ic-clothing.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(91, 31),
		image = IMAGE_SHEET,
	},
	["ic-clothing@2x"] = {
		name = "ic-clothing@2x",
		filename = "Icon/Navigation/primary/ic-clothing@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(871, 185),
		image = IMAGE_SHEET,
	},
	["ic-clothing@3x"] = {
		name = "ic-clothing@3x",
		filename = "Icon/Navigation/primary/ic-clothing@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(259, 487),
		image = IMAGE_SHEET,
	},
	["ic-costumes-on"] = {
		name = "ic-costumes-on",
		filename = "Icon/Navigation/primary/ic-costumes-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(637, 31),
		image = IMAGE_SHEET,
	},
	["ic-costumes-on@2x"] = {
		name = "ic-costumes-on@2x",
		filename = "Icon/Navigation/primary/ic-costumes-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1335, 127),
		image = IMAGE_SHEET,
	},
	["ic-costumes-on@3x"] = {
		name = "ic-costumes-on@3x",
		filename = "Icon/Navigation/primary/ic-costumes-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1205, 401),
		image = IMAGE_SHEET,
	},
	["ic-costumes"] = {
		name = "ic-costumes",
		filename = "Icon/Navigation/primary/ic-costumes.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(541, 31),
		image = IMAGE_SHEET,
	},
	["ic-costumes@2x"] = {
		name = "ic-costumes@2x",
		filename = "Icon/Navigation/primary/ic-costumes@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1815, 185),
		image = IMAGE_SHEET,
	},
	["ic-costumes@3x"] = {
		name = "ic-costumes@3x",
		filename = "Icon/Navigation/primary/ic-costumes@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(345, 401),
		image = IMAGE_SHEET,
	},
	["ic-recent-on"] = {
		name = "ic-recent-on",
		filename = "Icon/Navigation/primary/ic-recent-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1298, 31),
		image = IMAGE_SHEET,
	},
	["ic-recent-on@2x"] = {
		name = "ic-recent-on@2x",
		filename = "Icon/Navigation/primary/ic-recent-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(523, 243),
		image = IMAGE_SHEET,
	},
	["ic-recent-on@3x"] = {
		name = "ic-recent-on@3x",
		filename = "Icon/Navigation/primary/ic-recent-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1549, 487),
		image = IMAGE_SHEET,
	},
	["ic-recent"] = {
		name = "ic-recent",
		filename = "Icon/Navigation/primary/ic-recent.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1358, 31),
		image = IMAGE_SHEET,
	},
	["ic-recent@2x"] = {
		name = "ic-recent@2x",
		filename = "Icon/Navigation/primary/ic-recent@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 243),
		image = IMAGE_SHEET,
	},
	["ic-recent@3x"] = {
		name = "ic-recent@3x",
		filename = "Icon/Navigation/primary/ic-recent@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1807, 487),
		image = IMAGE_SHEET,
	},
	["ic-close"] = {
		name = "ic-close",
		filename = "Icon/others/ic-close.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(121, 31),
		image = IMAGE_SHEET,
	},
	["ic-close@2x"] = {
		name = "ic-close@2x",
		filename = "Icon/others/ic-close@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1699, 185),
		image = IMAGE_SHEET,
	},
	["ic-close@3x"] = {
		name = "ic-close@3x",
		filename = "Icon/others/ic-close@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(345, 487),
		image = IMAGE_SHEET,
	},
}

AESpriteSheet.getScale = function()
	return GuiService:GetResolutionScale()
end

AESpriteSheet.checkImageResolution = function(name, scale)
	local newImage = name .."@" ..scale .."x"

	if AESpriteSheet[newImage] then
		return AESpriteSheet[newImage]
	end
end

AESpriteSheet.getImage = function(name)
	local scale = AESpriteSheet.getScale()
	local newImage = AESpriteSheet[name]
	if scale > 2 then
		newImage = AESpriteSheet.checkImageResolution(name, 3) or AESpriteSheet.checkImageResolution(name, 2) or name
	elseif scale > 1 then
		newImage = AESpriteSheet.checkImageResolution(name, 2) or name
	end

	return newImage
end

return AESpriteSheet